FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

ENV DOCKER_BUILD=true

WORKDIR /app

COPY . ./

RUN dotnet restore MegaBulkUploader.csproj

RUN dotnet publish MegaBulkUploader.csproj -c Release -o /Publish/Docker /p:DOCKER_BUILD=true

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app

RUN apt-get update && \
    apt-get install -y \
    wget gnupg ca-certificates && \
    wget https://mega.nz/linux/repo/Debian_12/Release.key && \
    apt-key add Release.key && \
    echo "deb https://mega.nz/linux/repo/Debian_12/ ./" > /etc/apt/sources.list.d/megacmd.list && \
    apt-get update && \
    apt-get install -y megacmd && \
    rm -rf /var/lib/apt/lists/*

COPY --from=build /Publish/Docker .

EXPOSE 9662

ENTRYPOINT ["dotnet", "MegaBulkUploader.dll"]
